### ISSUE TITLE
gulp serve is running but browser can't connect

### ISSUE THREAD

**Issue by vizkid2005** [lakhia/rsvp-website#5]
Command line 
```
➜  rsvp-website git:(main) ✗ node_modules/gulp/bin/gulp.js serve
[23:39:46] Using gulpfile ~/p/rsvp-website/gulpfile.js
[23:39:46] Starting 'serve'...
[23:39:46] Starting 'watch'...
[23:39:46] Starting '<anonymous>'...
```

Browser
![gulp-error](https://github.com/lakhia/rsvp-website/assets/1933223/fd1c6f1c-6f91-4e5c-8d1b-e6896457be2a)

Machine - M1 Mac
node version - 20.6.1

What version of node should I be running ? 

## Steps followed 

1.  `git clone ...`
2. `npm install`
3. `node_modules/gulp/bin/gulp.js serve` // I don't have gulp installed globally (I don't believe that is necessary)

**Comment by lakhia** [comment]
I noticed that the gulp console message is not showing any info about the PHP dev server. My output is something like:

```
> node_modules/gulp/bin/gulp.js serve
[00:29:18] Using gulpfile ~/fun/rsvp/gulpfile.js
[00:29:18] Starting 'serve'...
[00:29:18] Starting 'watch'...
[00:29:18] Starting '<anonymous>'...
[Wed Jan 10 00:29:18 2024] PHP 8.3.0 Development Server (http://127.0.0.1:8010) started
[Wed Jan 10 00:29:18 2024] 127.0.0.1:53458 Accepted
[Wed Jan 10 00:29:18 2024] 127.0.0.1:53458 [200]: HEAD /
```

Can you please make sure php is in your path and can be found by `gulp` ?

**Comment by vizkid2005** [comment]
This was the missing missingp

> I noticed that the gulp console message is not showing any info about the PHP dev server. My output is something like:
> 
> ```
> > node_modules/gulp/bin/gulp.js serve
> [00:29:18] Using gulpfile ~/fun/rsvp/gulpfile.js
> [00:29:18] Starting 'serve'...
> [00:29:18] Starting 'watch'...
> [00:29:18] Starting '<anonymous>'...
> [Wed Jan 10 00:29:18 2024] PHP 8.3.0 Development Server (http://127.0.0.1:8010) started
> [Wed Jan 10 00:29:18 2024] 127.0.0.1:53458 Accepted
> [Wed Jan 10 00:29:18 2024] 127.0.0.1:53458 [200]: HEAD /
> ```
> 
> Can you please make sure php is in your path and can be found by `gulp` ?

This was the missing piece. Addressed it in a pull request

https://github.com/lakhia/rsvp-website/pull/6

Please review
